import type { Language } from "@/components/ui/language-toggle";

export type { Language } from "@/components/ui/language-toggle";

export const siteCopy = {
  ru: {
    announcementUpdated: "Прайс обновлён",
    announcementExtra: "Цены и наличие уточняйте у менеджера",
    navPrice: "Прайс-лист",
    navNewItems: "Новинки",
    contact: "Связаться",
    homeLabel: "UnB computers — на главную",
    topLabel: "UnB computers — наверх",
    heroVisualLabel: "Фирменный знак UnB computers",
    eyebrow: ["Техника", "Комплектующие", "Сервис"],
    heroTitle: ["Технологии,", "которые", "работают."],
    heroLead: "Компьютеры, комплектующие и периферия для дома и бизнеса — с понятными ценами, гарантией и человеческой консультацией.",
    downloadPrice: "Скачать прайс",
    price: {
      kicker: "Актуальный прайс",
      title: ["Один файл.", "Всегда свежие цены."],
      description: "Скачайте полный список товаров с артикулами, категориями, ценами, наличием и условиями гарантии. Формат открывается в Excel и Google Sheets.",
      features: [
        "Удобная таблица с фильтрами",
        "Цены в USD и KGS",
        "Поддержка XLS и XLSX",
        "Отдельная инструкция по обновлению",
      ],
      fileLabel: "ПРАЙС-ЛИСТ",
      versionLabel: "Версия",
      updatedLabel: "обновлено",
      format: "Формат",
      update: "Обновление",
      access: "Доступ",
      frequency: "ежедневно",
      free: "Свободный",
      download: "Скачать актуальный прайс",
      note: "После скачивания уточните финальную цену и наличие у менеджера.",
    },
    newItems: {
      kicker: "Новое в прайсе",
      title: "Новинки",
      aria: "Новинки прайс-листа",
      emptyCount: "Пока пусто",
      empty: "Новые товары появятся после следующего обновления прайса.",
      positionOne: "позиция",
      positionFew: "позиции",
      positionMany: "позиций",
    },
    contactBlock: {
      kicker: "Нужна помощь с выбором?",
      title: "Расскажите задачу —",
      accent: "подберём решение.",
      description: "Напишите менеджеру, чтобы уточнить наличие, финальную цену и подобрать подходящее решение.",
      button: "Написать в Telegram",
    },
    footerDescription: "Компьютеры и комплектующие для дома и бизнеса.",
    backToTop: "Наверх ↑",
  },
  en: {
    announcementUpdated: "Price updated",
    announcementExtra: "Ask the manager about prices and availability",
    navPrice: "Price list",
    navNewItems: "New arrivals",
    contact: "Contact",
    homeLabel: "UnB computers — home",
    topLabel: "UnB computers — back to top",
    heroVisualLabel: "UnB computers brand mark",
    eyebrow: ["Hardware", "Components", "Service"],
    heroTitle: ["Technology,", "that", "works."],
    heroLead: "Computers, components and peripherals for home and business — with clear prices, warranty and human support.",
    downloadPrice: "Download price list",
    price: {
      kicker: "Current price list",
      title: ["One file.", "Always up to date."],
      description: "Download the complete product list with SKUs, categories, prices, availability and warranty terms. Opens in Excel and Google Sheets.",
      features: [
        "Convenient table with filters",
        "Prices in USD and KGS",
        "XLS and XLSX supported",
        "Separate update instructions",
      ],
      fileLabel: "PRICE LIST",
      versionLabel: "Version",
      updatedLabel: "updated",
      format: "Format",
      update: "Updates",
      access: "Access",
      frequency: "daily",
      free: "Free",
      download: "Download current price list",
      note: "After downloading, confirm the final price and availability with the manager.",
    },
    newItems: {
      kicker: "New in the price list",
      title: "New arrivals",
      aria: "New products in the price list",
      emptyCount: "Nothing yet",
      empty: "New products will appear after the next price list update.",
      positionOne: "item",
      positionFew: "items",
      positionMany: "items",
    },
    contactBlock: {
      kicker: "Need help choosing?",
      title: "Tell us what you need —",
      accent: "we’ll find the right solution.",
      description: "Message the manager to check availability, confirm the final price and find the right setup.",
      button: "Write on Telegram",
    },
    footerDescription: "Computers and components for home and business.",
    backToTop: "Back to top ↑",
  },
} as const;

export type SiteCopy = (typeof siteCopy)[Language];
